function datahandle = prepareDatahandleForIntegration(rhs, varargin)
%datahandle = PREPAREDATAHANDLEFORINTEGRATION(rhs)
%datahandle = PREPAREDATAHANDLEFORINTEGRATION(rhs, 'integrator', integrator, ...)
%datahandle = PREPAREDATAHANDLEFORINTEGRATION(rhs, 'options', odeopts, ...)
%
%Prepare ODE RHS for integration with IFDIFF.
%
%INPUT:
%   rhs - Name or handle to RHS.
%   May be specified as a filename. Path and extension are optional, as long as the name can be resolved by MATLAB.
%   May be specified as a handle to the RHS function (must not be anonymous, i.e. @myRhs not @(t,y,p) myRhs(t,y,p)).
%       1xN char array | string scalar | function_handle
%
%   varargin - User options passed as key-value pairs.
%       func(mandatoryArgs, ..., 'key1', val1, 'key2', val2, ...)
%
%OPTIONS:
%   integrator - Name or handle to the integrator that IFDIFF should use. All MATLAB ODE solvers are supported.
%       1xN char array | string scalar | function_handle
%       default (from config): ode45
%
%   options - MATLAB ODE options to be used by the integrator.
%       struct (as generated by odeset)
%       default (from config): 'AbsTol'=1e-12, 'RelTol'=1e-4
%
%OUTPUT:
%   datahandle - Struct containing the prepared RHS ready for integration with IFDIFF.
%   Call sol = solveODE(datahandle, tspan, initialvalues, parameters) to compute a solution of the ODE with IFDIFF.
%       struct (with .getData() and .setData(data) function handles to emulate a handle class using closures)
%
%See also SOLVEODE.

preprocessed = preprocess(prepareDatahandleForIntegration_getRhsFilename(rhs));

% Prepare integration, initialize struct.
datahandle = createDatahandle(preprocessed);

% Set function handles for RHS and OutputFcn and handle varargin (odeOptions, integrator).
prepareDatahandleForIntegration_setUpIntegrator(datahandle, varargin{:});

% Check whether rhs has three inputs (i.e. rhs(t, y, p)).
prepareDatahandleForIntegration_checkRhs(datahandle);
end
