function jumpFunctionHandle = solveODE_computeJumpFunction(datahandle, factory, sI)
data = datahandle.getData();
signature = SwitchingFunctionSignature( ...
    data.mtreeplus{2,1}, ...
    data.SWP_detection.switch_cond_t1(1:sI), ...
    data.SWP_detection.ctrlif_index_t1(1:sI), ...
    data.SWP_detection.function_index_t1(1:sI) ...
    );
jumpFunctionHandle = factory.get(signature, data.SWP_detection.jumpConditions);
end
