classdef JumpFunctionCreator < FixedBranchingFunctionCreator
    methods
        % Constructor
        function this = JumpFunctionCreator(functionData, signature, writePath)
            config = makeConfig();
            this = this@FixedBranchingFunctionCreator( ...
                functionData, ...
                signature, ...
                writePath, ...
                config.jump.jumpFunctionNamePrefix, ...
                config.jump.jumpFunctionOutputName);
        end

        function this = handleLastCtrlif(this)
            this = this.handleHelperCallsBeforeCtrlif(this.numCtrlif, true);
            this = this.fixBranching(this.numCtrlif);

            this.exportMtreeArray{this.funcIter.idxMtreeCallerExport} = replaceCtrljumpByReturn( ...
                this.exportMtreeArray{this.funcIter.idxMtreeCallerExport}, ...
                this.signature.ctrlifIndex(this.numCtrlif), ...
                this.functionData.ctrljumpInfo);
        end
    end
end

