classdef IFDIFFDerivativeFiniteDifferences < IFDIFFDerivative
    %this = IFDIFFDERIVATIVEFINITEDIFFERENCES(datahandle, f, step)
    %
    %Compute derivatives w.r.t. t, y, p for functions generated by IFDIFF (i.e. rhs, switching, jump, submodel).
    %First order forward finite differences are used for the computation.
    %
    %INPUT:
    %   datahandle - Provides signature for forced branching if function contains ctrlifs (only the case for rhs).
    %       struct
    %
    %   f - Function whose derivative will be computed. Signature must be: out = f(datahandle, t, y, p).
    %       function_handle
    %
    %   step - Step size information for the finite difference method. Should always come from a call to generateFDstep.
    %       struct

    properties (Access=public)
        datahandle
        f % out = f(datahandle, t, y, p)
        step % from generateFDstep
    end
    methods (Access=public)
        function this = IFDIFFDerivativeFiniteDifferences(datahandle, f, step)
            if nargin == 0
                return
            end

            this.datahandle = datahandle;
            this.f = f;
            this.step = step;
        end

        %% Derivatives
        % Note: Code for computing derivatives for different arguments (i.e. t,y,p) is deliberately duplicated here,
        % because these functions will be called many times by the integrator when solving the VDE and we want to avoid
        % performance loss due to overhead from anonymous functions.
        function df = dt(this, t, y, p, v)
            f0 = this.f(this.datahandle, t, y, p);

            dimf = length(f0);
            nd = size(v, 2);
            df = zeros(dimf, nd);

            h = this.ht(t);
            [v, h, normv, idxNonzero] = this.scaleDirections(t, v, h);
            if isempty(idxNonzero)
                return
            end

            for i=1:length(idxNonzero)
                fh = this.f(this.datahandle, v(:, i), y, p);
                df(:, idxNonzero(i)) = (fh - f0) ./ h(i);
            end
            df(:, idxNonzero) = df(:, idxNonzero) .* normv(idxNonzero);
        end
        function df = dy(this, t, y, p, v)
            f0 = this.f(this.datahandle, t, y, p);

            [dimf, nt] = size(f0);
            nd = size(v, 2);
            df = zeros(dimf, nd, nt);

            h = this.hy(y);
            [v, h, normv, idxNonzero] = this.scaleDirections(y, v, h);
            if isempty(idxNonzero)
                return
            end

            for i=1:length(idxNonzero)
                fh = this.f(this.datahandle, t, v(:, i), p);
                df(:, idxNonzero(i), :) = (fh - f0) ./ h(i);
            end
            df(:, idxNonzero, :) = df(:, idxNonzero, :) .* normv(idxNonzero);
        end
        function df = dp(this, t, y, p, v)
            f0 = this.f(this.datahandle, t, y, p);

            [dimf, nt] = size(f0);
            nd = size(v, 2);
            df = zeros(dimf, nd, nt);

            h = this.hp(p);
            [v, h, normv, idxNonzero] = this.scaleDirections(p, v, h);
            if isempty(idxNonzero)
                return
            end

            for i=1:length(idxNonzero)
                fh = this.f(this.datahandle, t, y, v(:, i));
                df(:, idxNonzero(i), :) = (fh - f0) ./ h(i);
            end
            df(:, idxNonzero, :) = df(:, idxNonzero, :) .* normv(idxNonzero);
        end
    end

    %% Helper functions
    methods (Static, Access=private)
        function [v, h, normv, idxNonzero] = scaleDirections(x, v, h)
            % Filter zero directions.
            normv = vecnorm(v, 2, 1);
            idxNonzero = find(normv);
            if isempty(idxNonzero)
                return
            end
            % Scale each non-zero direction to unit length.
            v = v(:, idxNonzero) ./ normv(idxNonzero);
            % Assume that h is a column vector which contains a step size for each component.
            % To determine the step size for an arbitrary direction v compute the scalar product of h and v.
            h = h' * v;
            v = x + v.*h;
        end
    end

    %% Step size
    methods (Access=private)
        function h = ht(this, t)
            if this.step.t_rel
                h = max(this.step.t_min, abs(t) .* this.step.t);
            else
                h = this.step.t;
            end
        end
        function h = hy(this, y)
            if this.step.y_rel
                h = max(this.step.y_min, abs(y) .* this.step.y);
            else
                h = this.step.y;
            end
        end
        function h = hp(this, p)
            if this.step.p_rel
                h = max(this.step.p_min, abs(p) .* this.step.p);
            else
                h = this.step.p;
            end
        end
    end
end
