classdef SwitchingFunctionCreator < FixedBranchingFunctionCreator
    %this = SWITCHINGFUNCTIONCREATOR(functionData, signature, writePath)
    %
    %Create switching function from a signature (one-time-use).
    %
    %INPUT:
    %   functionData - Data related to preprocessed functions used to create new functions.
    %       PreprocessedFunctionData
    %
    %   signature - Signature of the function to be created.
    %       BranchingSignature
    %
    %   writePath - Absolute path to directory in which the source code of the new function will be placed.
    %       char array

    methods
        % Constructor
        function this = SwitchingFunctionCreator(functionData, signature, writePath)
            config = makeConfig();
            this = this@FixedBranchingFunctionCreator( ...
                functionData, ...
                signature, ...
                writePath, ...
                config.switchingFunctionNamePrefix, ...
                config.switchingFunctionOutputName);
        end

        function this = handleLastCtrlif(this)
            % Set return value of function to monitored condition of last ctrlif in the signature.
            this = this.handleHelperCallsBeforeCtrlif(this.numCtrlif, true);
            ctrlifCallInfo = this.functionData.getCtrlifCallInfo( ...
                this.funcIter.idxMtreeCallerOriginal, ...
                this.signature.ctrlifIndex(this.numCtrlif));
            this.exportMtreeArray{this.funcIter.idxMtreeCallerExport} = replaceCtrlifByReturn( ...
                this.exportMtreeArray{this.funcIter.idxMtreeCallerExport}, ...
                this.functionOutputName, ...
                ctrlifCallInfo.rIndexEquals, ...
                ctrlifCallInfo.rIndexExpr, ...
                ctrlifCallInfo.rIndexArgs(1) ...
                );
        end
    end
end
