function y = ODEInitialValues

    y(1) = 0; % CoffeinSimulation|Organism|VenousBlood|Plasma|Caffeine
    y(2) = 0; % CoffeinSimulation|Organism|VenousBlood|Plasma|Caffeine-CYP1A2 Metabolite
    y(3) = 0; % CoffeinSimulation|Organism|VenousBlood|BloodCells|Caffeine
    y(4) = 0; % CoffeinSimulation|Organism|VenousBlood|BloodCells|Caffeine-CYP1A2 Metabolite
    y(5) = 0; % CoffeinSimulation|Organism|ArterialBlood|Plasma|Caffeine
    y(6) = 0; % CoffeinSimulation|Organism|ArterialBlood|Plasma|Caffeine-CYP1A2 Metabolite
    y(7) = 0; % CoffeinSimulation|Organism|ArterialBlood|BloodCells|Caffeine
    y(8) = 0; % CoffeinSimulation|Organism|ArterialBlood|BloodCells|Caffeine-CYP1A2 Metabolite
    y(9) = 0; % CoffeinSimulation|Organism|Gallbladder|Caffeine
    y(10) = 0; % CoffeinSimulation|Organism|Bone|Plasma|Caffeine
    y(11) = 0; % CoffeinSimulation|Organism|Bone|Plasma|Caffeine-CYP1A2 Metabolite
    y(12) = 0; % CoffeinSimulation|Organism|Bone|BloodCells|Caffeine
    y(13) = 0; % CoffeinSimulation|Organism|Bone|BloodCells|Caffeine-CYP1A2 Metabolite
    y(14) = 0; % CoffeinSimulation|Organism|Bone|Interstitial|Caffeine
    y(15) = 0; % CoffeinSimulation|Organism|Bone|Intracellular|Caffeine
    y(16) = 0; % CoffeinSimulation|Organism|Bone|Intracellular|Caffeine-CYP1A2 Metabolite
    y(17) = 0; % CoffeinSimulation|Organism|Brain|Plasma|Caffeine
    y(18) = 0; % CoffeinSimulation|Organism|Brain|Plasma|Caffeine-CYP1A2 Metabolite
    y(19) = 0; % CoffeinSimulation|Organism|Brain|BloodCells|Caffeine
    y(20) = 0; % CoffeinSimulation|Organism|Brain|BloodCells|Caffeine-CYP1A2 Metabolite
    y(21) = 0; % CoffeinSimulation|Organism|Brain|Interstitial|Caffeine
    y(22) = 0; % CoffeinSimulation|Organism|Brain|Intracellular|Caffeine
    y(23) = 0; % CoffeinSimulation|Organism|Brain|Intracellular|Caffeine-CYP1A2 Metabolite
    y(24) = 0; % CoffeinSimulation|Organism|Fat|Plasma|Caffeine
    y(25) = 0; % CoffeinSimulation|Organism|Fat|Plasma|Caffeine-CYP1A2 Metabolite
    y(26) = 0; % CoffeinSimulation|Organism|Fat|BloodCells|Caffeine
    y(27) = 0; % CoffeinSimulation|Organism|Fat|BloodCells|Caffeine-CYP1A2 Metabolite
    y(28) = 0; % CoffeinSimulation|Organism|Fat|Interstitial|Caffeine
    y(29) = 0; % CoffeinSimulation|Organism|Fat|Intracellular|Caffeine
    y(30) = 0; % CoffeinSimulation|Organism|Fat|Intracellular|Caffeine-CYP1A2 Metabolite
    y(31) = 0; % CoffeinSimulation|Organism|Gonads|Plasma|Caffeine
    y(32) = 0; % CoffeinSimulation|Organism|Gonads|Plasma|Caffeine-CYP1A2 Metabolite
    y(33) = 0; % CoffeinSimulation|Organism|Gonads|BloodCells|Caffeine
    y(34) = 0; % CoffeinSimulation|Organism|Gonads|BloodCells|Caffeine-CYP1A2 Metabolite
    y(35) = 0; % CoffeinSimulation|Organism|Gonads|Interstitial|Caffeine
    y(36) = 0; % CoffeinSimulation|Organism|Gonads|Intracellular|Caffeine
    y(37) = 0; % CoffeinSimulation|Organism|Gonads|Intracellular|Caffeine-CYP1A2 Metabolite
    y(38) = 0; % CoffeinSimulation|Organism|Heart|Plasma|Caffeine
    y(39) = 0; % CoffeinSimulation|Organism|Heart|Plasma|Caffeine-CYP1A2 Metabolite
    y(40) = 0; % CoffeinSimulation|Organism|Heart|BloodCells|Caffeine
    y(41) = 0; % CoffeinSimulation|Organism|Heart|BloodCells|Caffeine-CYP1A2 Metabolite
    y(42) = 0; % CoffeinSimulation|Organism|Heart|Interstitial|Caffeine
    y(43) = 0; % CoffeinSimulation|Organism|Heart|Intracellular|Caffeine
    y(44) = 0; % CoffeinSimulation|Organism|Heart|Intracellular|Caffeine-CYP1A2 Metabolite
    y(45) = 0; % CoffeinSimulation|Organism|Kidney|Plasma|Caffeine
    y(46) = 0; % CoffeinSimulation|Organism|Kidney|Plasma|Caffeine-CYP1A2 Metabolite
    y(47) = 0; % CoffeinSimulation|Organism|Kidney|BloodCells|Caffeine
    y(48) = 0; % CoffeinSimulation|Organism|Kidney|BloodCells|Caffeine-CYP1A2 Metabolite
    y(49) = 0; % CoffeinSimulation|Organism|Kidney|Interstitial|Caffeine
    y(50) = 0; % CoffeinSimulation|Organism|Kidney|Intracellular|Caffeine
    y(51) = 0; % CoffeinSimulation|Organism|Kidney|Intracellular|Caffeine-CYP1A2 Metabolite
    y(52) = 0; % CoffeinSimulation|Organism|Kidney|Urine|Caffeine
    y(53) = 0.0473894; % CoffeinSimulation|Organism|Lumen|Stomach|Liquid
    y(54) = 0; % CoffeinSimulation|Organism|Lumen|Stomach|Caffeine
    y(55) = 0; % CoffeinSimulation|Organism|Lumen|Stomach|Caffeine-CYP1A2 Metabolite
    y(56) = 0.0120515; % CoffeinSimulation|Organism|Lumen|Duodenum|Liquid
    y(57) = 0; % CoffeinSimulation|Organism|Lumen|Duodenum|Caffeine
    y(58) = 0; % CoffeinSimulation|Organism|Lumen|Duodenum|Caffeine|Oral mass absorbed segment
    y(59) = 0; % CoffeinSimulation|Organism|Lumen|Duodenum|Caffeine-CYP1A2 Metabolite
    y(60) = 0.025782; % CoffeinSimulation|Organism|Lumen|UpperJejunum|Liquid
    y(61) = 0; % CoffeinSimulation|Organism|Lumen|UpperJejunum|Caffeine
    y(62) = 0; % CoffeinSimulation|Organism|Lumen|UpperJejunum|Caffeine|Oral mass absorbed segment
    y(63) = 0; % CoffeinSimulation|Organism|Lumen|UpperJejunum|Caffeine-CYP1A2 Metabolite
    y(64) = 0.0225637; % CoffeinSimulation|Organism|Lumen|LowerJejunum|Liquid
    y(65) = 0; % CoffeinSimulation|Organism|Lumen|LowerJejunum|Caffeine
    y(66) = 0; % CoffeinSimulation|Organism|Lumen|LowerJejunum|Caffeine|Oral mass absorbed segment
    y(67) = 0; % CoffeinSimulation|Organism|Lumen|LowerJejunum|Caffeine-CYP1A2 Metabolite
    y(68) = 0.0270026; % CoffeinSimulation|Organism|Lumen|UpperIleum|Liquid
    y(69) = 0; % CoffeinSimulation|Organism|Lumen|UpperIleum|Caffeine
    y(70) = 0; % CoffeinSimulation|Organism|Lumen|UpperIleum|Caffeine|Oral mass absorbed segment
    y(71) = 0; % CoffeinSimulation|Organism|Lumen|UpperIleum|Caffeine-CYP1A2 Metabolite
    y(72) = 0.0193483; % CoffeinSimulation|Organism|Lumen|LowerIleum|Liquid
    y(73) = 0; % CoffeinSimulation|Organism|Lumen|LowerIleum|Caffeine
    y(74) = 0; % CoffeinSimulation|Organism|Lumen|LowerIleum|Caffeine|Oral mass absorbed segment
    y(75) = 0; % CoffeinSimulation|Organism|Lumen|LowerIleum|Caffeine-CYP1A2 Metabolite
    y(76) = 0.00130513; % CoffeinSimulation|Organism|Lumen|Caecum|Liquid
    y(77) = 0; % CoffeinSimulation|Organism|Lumen|Caecum|Caffeine
    y(78) = 0; % CoffeinSimulation|Organism|Lumen|Caecum|Caffeine|Oral mass absorbed segment
    y(79) = 0; % CoffeinSimulation|Organism|Lumen|Caecum|Caffeine-CYP1A2 Metabolite
    y(80) = 0.00364956; % CoffeinSimulation|Organism|Lumen|ColonAscendens|Liquid
    y(81) = 0; % CoffeinSimulation|Organism|Lumen|ColonAscendens|Caffeine
    y(82) = 0; % CoffeinSimulation|Organism|Lumen|ColonAscendens|Caffeine|Oral mass absorbed segment
    y(83) = 0; % CoffeinSimulation|Organism|Lumen|ColonAscendens|Caffeine-CYP1A2 Metabolite
    y(84) = 0.00454008; % CoffeinSimulation|Organism|Lumen|ColonTransversum|Liquid
    y(85) = 0; % CoffeinSimulation|Organism|Lumen|ColonTransversum|Caffeine
    y(86) = 0; % CoffeinSimulation|Organism|Lumen|ColonTransversum|Caffeine|Oral mass absorbed segment
    y(87) = 0; % CoffeinSimulation|Organism|Lumen|ColonTransversum|Caffeine-CYP1A2 Metabolite
    y(88) = 0.00156276; % CoffeinSimulation|Organism|Lumen|ColonDescendens|Liquid
    y(89) = 0; % CoffeinSimulation|Organism|Lumen|ColonDescendens|Caffeine
    y(90) = 0; % CoffeinSimulation|Organism|Lumen|ColonDescendens|Caffeine|Oral mass absorbed segment
    y(91) = 0; % CoffeinSimulation|Organism|Lumen|ColonDescendens|Caffeine-CYP1A2 Metabolite
    y(92) = 0.00193383; % CoffeinSimulation|Organism|Lumen|ColonSigmoid|Liquid
    y(93) = 0; % CoffeinSimulation|Organism|Lumen|ColonSigmoid|Caffeine
    y(94) = 0; % CoffeinSimulation|Organism|Lumen|ColonSigmoid|Caffeine|Oral mass absorbed segment
    y(95) = 0; % CoffeinSimulation|Organism|Lumen|ColonSigmoid|Caffeine-CYP1A2 Metabolite
    y(96) = 0.000525579; % CoffeinSimulation|Organism|Lumen|Rectum|Liquid
    y(97) = 0; % CoffeinSimulation|Organism|Lumen|Rectum|Caffeine
    y(98) = 0; % CoffeinSimulation|Organism|Lumen|Rectum|Caffeine|Oral mass absorbed segment
    y(99) = 0; % CoffeinSimulation|Organism|Lumen|Rectum|Caffeine-CYP1A2 Metabolite
    y(100) = 0; % CoffeinSimulation|Organism|Lumen|Feces|Liquid
    y(101) = 0; % CoffeinSimulation|Organism|Lumen|Feces|Caffeine
    y(102) = 0; % CoffeinSimulation|Organism|Stomach|Plasma|Caffeine
    y(103) = 0; % CoffeinSimulation|Organism|Stomach|Plasma|Caffeine-CYP1A2 Metabolite
    y(104) = 0; % CoffeinSimulation|Organism|Stomach|BloodCells|Caffeine
    y(105) = 0; % CoffeinSimulation|Organism|Stomach|BloodCells|Caffeine-CYP1A2 Metabolite
    y(106) = 0; % CoffeinSimulation|Organism|Stomach|Interstitial|Caffeine
    y(107) = 0; % CoffeinSimulation|Organism|Stomach|Intracellular|Caffeine
    y(108) = 0; % CoffeinSimulation|Organism|Stomach|Intracellular|Caffeine-CYP1A2 Metabolite
    y(109) = 0; % CoffeinSimulation|Organism|SmallIntestine|Plasma|Caffeine
    y(110) = 0; % CoffeinSimulation|Organism|SmallIntestine|Plasma|Caffeine-CYP1A2 Metabolite
    y(111) = 0; % CoffeinSimulation|Organism|SmallIntestine|BloodCells|Caffeine
    y(112) = 0; % CoffeinSimulation|Organism|SmallIntestine|BloodCells|Caffeine-CYP1A2 Metabolite
    y(113) = 0; % CoffeinSimulation|Organism|SmallIntestine|Interstitial|Caffeine
    y(114) = 0; % CoffeinSimulation|Organism|SmallIntestine|Intracellular|Caffeine
    y(115) = 0; % CoffeinSimulation|Organism|SmallIntestine|Intracellular|Caffeine-CYP1A2 Metabolite
    y(116) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|Duodenum|Plasma|Caffeine
    y(117) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|Duodenum|Plasma|Caffeine-CYP1A2 Metabolite
    y(118) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|Duodenum|BloodCells|Caffeine
    y(119) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|Duodenum|BloodCells|Caffeine-CYP1A2 Metabolite
    y(120) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|Duodenum|Interstitial|Caffeine
    y(121) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|Duodenum|Intracellular|Caffeine
    y(122) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|Duodenum|Intracellular|Caffeine-CYP1A2 Metabolite
    y(123) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperJejunum|Plasma|Caffeine
    y(124) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperJejunum|Plasma|Caffeine-CYP1A2 Metabolite
    y(125) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperJejunum|BloodCells|Caffeine
    y(126) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperJejunum|BloodCells|Caffeine-CYP1A2 Metabolite
    y(127) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperJejunum|Interstitial|Caffeine
    y(128) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperJejunum|Intracellular|Caffeine
    y(129) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperJejunum|Intracellular|Caffeine-CYP1A2 Metabolite
    y(130) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerJejunum|Plasma|Caffeine
    y(131) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerJejunum|Plasma|Caffeine-CYP1A2 Metabolite
    y(132) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerJejunum|BloodCells|Caffeine
    y(133) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerJejunum|BloodCells|Caffeine-CYP1A2 Metabolite
    y(134) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerJejunum|Interstitial|Caffeine
    y(135) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerJejunum|Intracellular|Caffeine
    y(136) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerJejunum|Intracellular|Caffeine-CYP1A2 Metabolite
    y(137) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperIleum|Plasma|Caffeine
    y(138) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperIleum|Plasma|Caffeine-CYP1A2 Metabolite
    y(139) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperIleum|BloodCells|Caffeine
    y(140) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperIleum|BloodCells|Caffeine-CYP1A2 Metabolite
    y(141) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperIleum|Interstitial|Caffeine
    y(142) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperIleum|Intracellular|Caffeine
    y(143) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|UpperIleum|Intracellular|Caffeine-CYP1A2 Metabolite
    y(144) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerIleum|Plasma|Caffeine
    y(145) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerIleum|Plasma|Caffeine-CYP1A2 Metabolite
    y(146) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerIleum|BloodCells|Caffeine
    y(147) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerIleum|BloodCells|Caffeine-CYP1A2 Metabolite
    y(148) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerIleum|Interstitial|Caffeine
    y(149) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerIleum|Intracellular|Caffeine
    y(150) = 0; % CoffeinSimulation|Organism|SmallIntestine|Mucosa|LowerIleum|Intracellular|Caffeine-CYP1A2 Metabolite
    y(151) = 0; % CoffeinSimulation|Organism|LargeIntestine|Plasma|Caffeine
    y(152) = 0; % CoffeinSimulation|Organism|LargeIntestine|Plasma|Caffeine-CYP1A2 Metabolite
    y(153) = 0; % CoffeinSimulation|Organism|LargeIntestine|BloodCells|Caffeine
    y(154) = 0; % CoffeinSimulation|Organism|LargeIntestine|BloodCells|Caffeine-CYP1A2 Metabolite
    y(155) = 0; % CoffeinSimulation|Organism|LargeIntestine|Interstitial|Caffeine
    y(156) = 0; % CoffeinSimulation|Organism|LargeIntestine|Intracellular|Caffeine
    y(157) = 0; % CoffeinSimulation|Organism|LargeIntestine|Intracellular|Caffeine-CYP1A2 Metabolite
    y(158) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Caecum|Plasma|Caffeine
    y(159) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Caecum|Plasma|Caffeine-CYP1A2 Metabolite
    y(160) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Caecum|BloodCells|Caffeine
    y(161) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Caecum|BloodCells|Caffeine-CYP1A2 Metabolite
    y(162) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Caecum|Interstitial|Caffeine
    y(163) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Caecum|Intracellular|Caffeine
    y(164) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Caecum|Intracellular|Caffeine-CYP1A2 Metabolite
    y(165) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonAscendens|Plasma|Caffeine
    y(166) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonAscendens|Plasma|Caffeine-CYP1A2 Metabolite
    y(167) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonAscendens|BloodCells|Caffeine
    y(168) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonAscendens|BloodCells|Caffeine-CYP1A2 Metabolite
    y(169) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonAscendens|Interstitial|Caffeine
    y(170) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonAscendens|Intracellular|Caffeine
    y(171) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonAscendens|Intracellular|Caffeine-CYP1A2 Metabolite
    y(172) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonTransversum|Plasma|Caffeine
    y(173) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonTransversum|Plasma|Caffeine-CYP1A2 Metabolite
    y(174) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonTransversum|BloodCells|Caffeine
    y(175) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonTransversum|BloodCells|Caffeine-CYP1A2 Metabolite
    y(176) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonTransversum|Interstitial|Caffeine
    y(177) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonTransversum|Intracellular|Caffeine
    y(178) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonTransversum|Intracellular|Caffeine-CYP1A2 Metabolite
    y(179) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonDescendens|Plasma|Caffeine
    y(180) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonDescendens|Plasma|Caffeine-CYP1A2 Metabolite
    y(181) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonDescendens|BloodCells|Caffeine
    y(182) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonDescendens|BloodCells|Caffeine-CYP1A2 Metabolite
    y(183) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonDescendens|Interstitial|Caffeine
    y(184) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonDescendens|Intracellular|Caffeine
    y(185) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonDescendens|Intracellular|Caffeine-CYP1A2 Metabolite
    y(186) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonSigmoid|Plasma|Caffeine
    y(187) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonSigmoid|Plasma|Caffeine-CYP1A2 Metabolite
    y(188) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonSigmoid|BloodCells|Caffeine
    y(189) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonSigmoid|BloodCells|Caffeine-CYP1A2 Metabolite
    y(190) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonSigmoid|Interstitial|Caffeine
    y(191) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonSigmoid|Intracellular|Caffeine
    y(192) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|ColonSigmoid|Intracellular|Caffeine-CYP1A2 Metabolite
    y(193) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Rectum|Plasma|Caffeine
    y(194) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Rectum|Plasma|Caffeine-CYP1A2 Metabolite
    y(195) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Rectum|BloodCells|Caffeine
    y(196) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Rectum|BloodCells|Caffeine-CYP1A2 Metabolite
    y(197) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Rectum|Interstitial|Caffeine
    y(198) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Rectum|Intracellular|Caffeine
    y(199) = 0; % CoffeinSimulation|Organism|LargeIntestine|Mucosa|Rectum|Intracellular|Caffeine-CYP1A2 Metabolite
    y(200) = 0; % CoffeinSimulation|Organism|Liver|Periportal|Plasma|Caffeine
    y(201) = 0; % CoffeinSimulation|Organism|Liver|Periportal|Plasma|Caffeine-CYP1A2 Metabolite
    y(202) = 0; % CoffeinSimulation|Organism|Liver|Periportal|BloodCells|Caffeine
    y(203) = 0; % CoffeinSimulation|Organism|Liver|Periportal|BloodCells|Caffeine-CYP1A2 Metabolite
    y(204) = 0; % CoffeinSimulation|Organism|Liver|Periportal|Interstitial|Caffeine
    y(205) = 0; % CoffeinSimulation|Organism|Liver|Periportal|Intracellular|Caffeine
    y(206) = 0; % CoffeinSimulation|Organism|Liver|Periportal|Intracellular|Caffeine-CYP1A2 Metabolite
    y(207) = 0; % CoffeinSimulation|Organism|Liver|Pericentral|Plasma|Caffeine
    y(208) = 0; % CoffeinSimulation|Organism|Liver|Pericentral|Plasma|Caffeine-CYP1A2 Metabolite
    y(209) = 0; % CoffeinSimulation|Organism|Liver|Pericentral|BloodCells|Caffeine
    y(210) = 0; % CoffeinSimulation|Organism|Liver|Pericentral|BloodCells|Caffeine-CYP1A2 Metabolite
    y(211) = 0; % CoffeinSimulation|Organism|Liver|Pericentral|Interstitial|Caffeine
    y(212) = 0; % CoffeinSimulation|Organism|Liver|Pericentral|Intracellular|Caffeine
    y(213) = 0; % CoffeinSimulation|Organism|Liver|Pericentral|Intracellular|Caffeine-CYP1A2 Metabolite
    y(214) = 0; % CoffeinSimulation|Organism|Lung|Plasma|Caffeine
    y(215) = 0; % CoffeinSimulation|Organism|Lung|Plasma|Caffeine-CYP1A2 Metabolite
    y(216) = 0; % CoffeinSimulation|Organism|Lung|BloodCells|Caffeine
    y(217) = 0; % CoffeinSimulation|Organism|Lung|BloodCells|Caffeine-CYP1A2 Metabolite
    y(218) = 0; % CoffeinSimulation|Organism|Lung|Interstitial|Caffeine
    y(219) = 0; % CoffeinSimulation|Organism|Lung|Intracellular|Caffeine
    y(220) = 0; % CoffeinSimulation|Organism|Lung|Intracellular|Caffeine-CYP1A2 Metabolite
    y(221) = 0; % CoffeinSimulation|Organism|Muscle|Plasma|Caffeine
    y(222) = 0; % CoffeinSimulation|Organism|Muscle|Plasma|Caffeine-CYP1A2 Metabolite
    y(223) = 0; % CoffeinSimulation|Organism|Muscle|BloodCells|Caffeine
    y(224) = 0; % CoffeinSimulation|Organism|Muscle|BloodCells|Caffeine-CYP1A2 Metabolite
    y(225) = 0; % CoffeinSimulation|Organism|Muscle|Interstitial|Caffeine
    y(226) = 0; % CoffeinSimulation|Organism|Muscle|Intracellular|Caffeine
    y(227) = 0; % CoffeinSimulation|Organism|Muscle|Intracellular|Caffeine-CYP1A2 Metabolite
    y(228) = 0; % CoffeinSimulation|Organism|Pancreas|Plasma|Caffeine
    y(229) = 0; % CoffeinSimulation|Organism|Pancreas|Plasma|Caffeine-CYP1A2 Metabolite
    y(230) = 0; % CoffeinSimulation|Organism|Pancreas|BloodCells|Caffeine
    y(231) = 0; % CoffeinSimulation|Organism|Pancreas|BloodCells|Caffeine-CYP1A2 Metabolite
    y(232) = 0; % CoffeinSimulation|Organism|Pancreas|Interstitial|Caffeine
    y(233) = 0; % CoffeinSimulation|Organism|Pancreas|Intracellular|Caffeine
    y(234) = 0; % CoffeinSimulation|Organism|Pancreas|Intracellular|Caffeine-CYP1A2 Metabolite
    y(235) = 0; % CoffeinSimulation|Organism|PortalVein|Plasma|Caffeine
    y(236) = 0; % CoffeinSimulation|Organism|PortalVein|Plasma|Caffeine-CYP1A2 Metabolite
    y(237) = 0; % CoffeinSimulation|Organism|PortalVein|BloodCells|Caffeine
    y(238) = 0; % CoffeinSimulation|Organism|PortalVein|BloodCells|Caffeine-CYP1A2 Metabolite
    y(239) = 0; % CoffeinSimulation|Organism|Skin|Plasma|Caffeine
    y(240) = 0; % CoffeinSimulation|Organism|Skin|Plasma|Caffeine-CYP1A2 Metabolite
    y(241) = 0; % CoffeinSimulation|Organism|Skin|BloodCells|Caffeine
    y(242) = 0; % CoffeinSimulation|Organism|Skin|BloodCells|Caffeine-CYP1A2 Metabolite
    y(243) = 0; % CoffeinSimulation|Organism|Skin|Interstitial|Caffeine
    y(244) = 0; % CoffeinSimulation|Organism|Skin|Intracellular|Caffeine
    y(245) = 0; % CoffeinSimulation|Organism|Skin|Intracellular|Caffeine-CYP1A2 Metabolite
    y(246) = 0; % CoffeinSimulation|Organism|Spleen|Plasma|Caffeine
    y(247) = 0; % CoffeinSimulation|Organism|Spleen|Plasma|Caffeine-CYP1A2 Metabolite
    y(248) = 0; % CoffeinSimulation|Organism|Spleen|BloodCells|Caffeine
    y(249) = 0; % CoffeinSimulation|Organism|Spleen|BloodCells|Caffeine-CYP1A2 Metabolite
    y(250) = 0; % CoffeinSimulation|Organism|Spleen|Interstitial|Caffeine
    y(251) = 0; % CoffeinSimulation|Organism|Spleen|Intracellular|Caffeine
    y(252) = 0; % CoffeinSimulation|Organism|Spleen|Intracellular|Caffeine-CYP1A2 Metabolite
    y(253) = 0; % CoffeinSimulation|Organism|Saliva|Saliva|Caffeine
    y(254) = 0; % CoffeinSimulation|Organism|Saliva|SalivaGland|Caffeine
    y(255) = 1127.7; % CoffeinSimulation|Applications|3 mg per kg Infusion (10 min)|Application_1|Caffeine

    y=y';
