classDiagram
    Sensitivity o-- Solution : Describes switching behavior and nominal trajectory
    Sensitivity ..> Integrator : Calls to solve VDE (or ODE with disturbed inputs)
    Sensitivity ..> Derivative : Calls to compute switch updates and VDE RHS
    Integrator ..> Solution : Computes
    Derivative <|.. FiniteDifference : Implements
    class Sensitivity{
        +Solution nominal_trajectory
        +Integrator integrator
        +List~float~ switching_timepoints
        +function rhs
        +List~function~ switching_functions
        +List~function~ jump_functions
        +List~Derivatives~ derivative_rhs_submodels
        +List~Derivative~ derivative_switching_functions
        +List~Derivative~ derivative_jump_functions
        +List~int~ initial_value_indices_for_which_to_compute
        +List~int~ parameter_indices_for_which_to_compute
        +float initial_time
        +Matrix~float~ initial_value_sensitivity_initial_value
        +Matrix~float~ parameter_sensitivity_initial_value

        +evaluate(List~float~ timepoints) List~Vector~float~~ sensitivity_at_timepoints
        +get_dense_representation(List~float~ timepoints, List~Vector~float~~ sensitivity_at_timepoints) Solution
    }
    class Solution{
        +List~float~ timepoints
        +List~Vector~float~~ solution_at_timepoints
        +evaluate_dense(List~float~ timepoints) List~Vector~float~~ solution_at_timepoints
    }
    class Integrator{
        +function rhs
        +float initial_time
        +Vector~float~ initial_value
        +Struct options
        +solve(List~float~ timepoints) Solution
    }
    class Derivative{
        <<interface>>
        +function f
        +fdt(float t, Vector~float~ y, Vector~float~ p, float direction) Vector~float~ 
        +fdy(float t, Vector~float~ y, Vector~float~ p, Matrix~float~ direction) Matrix~float~ 
        +fdp(float t, Vector~float~ y, Vector~float~ p, Matrix~float~ direction) Matrix~float~ 
    }

    class FiniteDifference{
        +float step_size
        +get_step_size(t, y, p) Vector~float~
    }
