function solveODE_setupFunctionStores(datahandle)
%SOLVEODE_SETUPFUNCTIONSTORES(datahandle)
%
%Setup class instances for retrieving switching/jump/model functions.
%
%INPUT:
%   datahandle - Datahandle containing the preprocessed mtree and path information.
%       function_handle
%
%OUPUT:
%   codeGen - Field added to datahandle struct with the class instances.
%       struct

config = makeConfig();
data = datahandle.getData();

mtreeArray = data.mtreeplus(3, :);
functionNameArray = data.mtreeplus(2, :);
functionData = PreprocessedFunctionData(mtreeArray, functionNameArray);

switchFactory = FixedBranchingFunctionStore( ...
    functionData, ...
    data.paths.preprocessed_switchingFunction, ...
    config.switchingFunctionNamePrefix, ...
    @(functionData, signature) SwitchingFunctionCreator(functionData, signature, data.paths.preprocessed_switchingFunction));
jumpFactory = FixedBranchingFunctionStore( ...
    functionData, ...
    data.paths.preprocessed_jumpFunction, ...
    config.jump.jumpFunctionNamePrefix, ...
    @(functionData, signature) JumpFunctionCreator(functionData, signature, data.paths.preprocessed_jumpFunction));
modelFactory = FixedBranchingFunctionStore( ...
    functionData, ...
    data.paths.preprocessed_modelFunction, ...
    config.modelFunctionNamePrefix, ...
    @(functionData, signature) ModelFunctionCreator(functionData, signature, data.paths.preprocessed_modelFunction));

data.codeGen = struct( ...
    'switchFactory', switchFactory, ...
    'jumpFactory', jumpFactory, ...
    'modelFactory', modelFactory);
datahandle.setData(data);
end
