classdef SwitchingFunctionCreator < FunctionCreator
    methods
        % Constructor
        function this = SwitchingFunctionCreator(functionData, signature, writePath)
            config = makeConfig();
            this = this@FunctionCreator( ...
                functionData, ...
                signature, ...
                writePath, ...
                config.switchingFunctionNamePrefix, ...
                config.switchingFunctionOutputName);
        end

        function this = handleLastCtrlif(this)
            this = this.handleHelperCallsBeforeCtrlif(this.numCtrlif, true);
            ctrlifCallInfo = this.functionData.getCtrlifCallInfo( ...
                this.funcIter.idxMtreeCallerOriginal, ...
                this.signature.ctrlifIndex(this.numCtrlif));
            this.exportMtreeArray{this.funcIter.idxMtreeCallerExport} = replaceCtrlifByReturn( ...
                this.exportMtreeArray{this.funcIter.idxMtreeCallerExport}, ...
                this.functionOutputName, ...
                ctrlifCallInfo.rIndexEquals, ...
                ctrlifCallInfo.rIndexExpr, ...
                ctrlifCallInfo.rIndexArgs(1) ...
                );
        end
    end
end

