function mtree = adjustFunctionCall(mtree, newName, rIndexCall, rIndexArg3)

cIndex = mtree_cIndex();

% Adjust the function call
[mtree, ~] = mtree_createAndAdd_NewNode(mtree, ...
    rIndexCall, ...                     % from
    cIndex.indexLeftchild, ...                                       % from_types
    {mtree.K.ID, newName});

mtree = mtree_connectNodes(...
    mtree, ...
    rIndexCall,...
    rIndexArg3,...
    cIndex.indexRightchild);
end 
