function [mtreeCaller, idxMtreeFunction] = processFunctionIndex(this, functionIndex, idxMtreeCaller, mtreeCaller, adjustFunctionCall, setReturnValue, hash)

helperFunctionInfo = this.getHelperFunctionCallInfo(idxMtreeCaller, functionIndex);
idxMtreeFunction = this.functionIndexToIdxMtree(functionIndex, idxMtreeCaller);
if adjustFunctionCall
    newHelperFunctionName = createSwitchingFunctionName(this.functionNameArray{idxMtreeFunction}, hash);
    mtreeCaller = SwitchingFunctionFactory.adjustFunctionCall( ...
        mtreeCaller, ...
        newHelperFunctionName, ...
        helperFunctionInfo.rIndexCall, ...
        helperFunctionInfo.rIndexArgs(3) ...
        );
end

% For the caller mtree, we can set the result of the function call as the output
if setReturnValue
    mtreeCaller = SwitchingFunctionFactory.setFunctionCallAsReturnValue( ...
        mtreeCaller, ...
        helperFunctionInfo.rIndexEquals, ...
        helperFunctionInfo.rIndexExpr ...
        );
end
end

