function mtree = createHelperSwitchingFunction(mtree, newName)
cIndex = mtree_cIndex();

rIndex = struct('HEAD', struct(), 'BODY', struct());
rIndex.HEAD = mtree_rIndex_head(mtree, rIndex.HEAD);

[mtree, ~] = mtree_createAndAdd_NewNode( ...
    mtree, ...
    rIndex.HEAD.ETC2, ...                     % from
    cIndex.indexLeftchild, ...                % from_types
    {mtree.K.ID, newName} ...
);

mtree = mtree_connectNodes(...
    mtree, ...
    rIndex.HEAD.ETC2,...
    rIndex.HEAD.Arg(1,3),...
    cIndex.indexRightchild ...
);
end

